{
 "title": "Health",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cortlex.APM.AspNetSample - STAGING",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Current healthy states",
   "type": "alertlist",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "-ping google.com",
     "measurement": "app11",
     "query": "SELECT \"HealthStatusInt\"  AS IsAlive FROM \"monitor\".\"app11\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "-ping tut.by",
     "measurement": "app12",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current in progress checks",
   "type": "alertlist",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "alias": "-ping google.com",
     "measurement": "app11",
     "query": "SELECT \"HealthStatusInt\"  AS IsAlive FROM \"monitor\".\"app11\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "-ping tut.by",
     "measurement": "app12",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current unhealthy state",
   "type": "alertlist",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "alias": "-ping google.com",
     "measurement": "app11",
     "query": "SELECT \"HealthStatusInt\"  AS IsAlive FROM \"monitor\".\"app11\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "-ping tut.by",
     "measurement": "app12",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping healthcheck",
   "type": "graph",
   "description": "Check Ping Health Status",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "-ping google.com",
     "measurement": "application.health",
     "query": "SELECT \"HealthStatusInt\" FROM \"monitor\".\"appmetrics.internal__report_success\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "Cortlex.APM.AspNetSample" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "Development" },
      { "condition": "AND", "key": "server", "operator": "=", "value": "DESKTOP-035" }
     ]
    }
   ]
  },
  {
   "title": "Last PING unhealthy value",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "Status",
     "measurement": "application.health",
     "select": [
      [
       { "params": [ "HealthStatusString" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "app",
       "operator": "=",
       "value": "Cortlex.APM.Health.Publishers.InfluxDb"
      },
      { "condition": "AND", "key": "env", "operator": "=", "value": "Development" },
      { "condition": "AND", "key": "server", "operator": "=", "value": "DESKTOP-035" },
      { "condition": "AND", "key": "CheckType", "operator": "=", "value": "uri-group" },
      { "condition": "AND", "key": "HealthStatusString", "operator": "=", "value": "Degraded" },
      { "condition": "OR", "key": "HealthStatusString", "operator": "=", "value": "Unhealthy" }
     ]
    }
   ]
  },
  {
   "title": "Cortlex.APM.AspNetSample  - DEVELOPMENT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Current healthy checks",
   "type": "alertlist",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "-ping google.com",
     "measurement": "app11",
     "query": "SELECT \"HealthStatusInt\"  AS IsAlive FROM \"monitor\".\"app11\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "-ping tut.by",
     "measurement": "app12",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current \"In progress\" checks",
   "type": "alertlist",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 15 },
   "targets": [
    {
     "alias": "-ping google.com",
     "measurement": "app11",
     "query": "SELECT \"HealthStatusInt\"  AS IsAlive FROM \"monitor\".\"app11\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "-ping tut.by",
     "measurement": "app12",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current unhealthy state",
   "type": "alertlist",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 15 },
   "targets": [
    {
     "alias": "-ping google.com",
     "measurement": "app11",
     "query": "SELECT \"HealthStatusInt\"  AS IsAlive FROM \"monitor\".\"app11\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "-ping tut.by",
     "measurement": "app12",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping Health Check",
   "type": "graph",
   "description": "Check Ping Health Status",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "-ping google.com",
     "measurement": "application.health",
     "query": "SELECT \"HealthStatusInt\" FROM \"monitor\".\"appmetrics.internal__report_success\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "Cortlex.APM.AspNetSample" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "Development" },
      { "condition": "AND", "key": "server", "operator": "=", "value": "DESKTOP-035" }
     ]
    }
   ]
  },
  {
   "title": "Last PING unhealthy value",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "alias": "Status",
     "measurement": "application.health",
     "select": [
      [
       { "params": [ "HealthStatusString" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "app",
       "operator": "=",
       "value": "Cortlex.APM.Health.Publishers.InfluxDb"
      },
      { "condition": "AND", "key": "env", "operator": "=", "value": "Development" },
      { "condition": "AND", "key": "server", "operator": "=", "value": "DESKTOP-035" },
      { "condition": "AND", "key": "CheckType", "operator": "=", "value": "uri-group" },
      { "condition": "AND", "key": "HealthStatusString", "operator": "=", "value": "Degraded" },
      { "condition": "OR", "key": "HealthStatusString", "operator": "=", "value": "Unhealthy" }
     ]
    }
   ]
  }
 ]
}