{
 "title": "Health",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current healthy checks",
   "type": "alertlist",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "-ping google.com",
     "measurement": "app11",
     "query": "SELECT \"HealthStatusInt\"  AS IsAlive FROM \"monitor\".\"app11\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "-ping tut.by",
     "measurement": "app12",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current \"In progress\" checks",
   "type": "alertlist",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "alias": "-ping google.com",
     "measurement": "app11",
     "query": "SELECT \"HealthStatusInt\"  AS IsAlive FROM \"monitor\".\"app11\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "-ping tut.by",
     "measurement": "app12",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current unhealthy state",
   "type": "alertlist",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "alias": "-ping google.com",
     "measurement": "app11",
     "query": "SELECT \"HealthStatusInt\"  AS IsAlive FROM \"monitor\".\"app11\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "-ping tut.by",
     "measurement": "app12",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping Health Check",
   "type": "graph",
   "description": "Check Ping Health Status",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "-ping google.com",
     "measurement": "Cortlex.APM.HealthCheсks.AspNetSample.uri-group",
     "query": "SELECT \"HealthStatusInt\"  AS IsAlive FROM \"monitor\".\"app11\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DB Health Check",
   "type": "graph",
   "description": "Check Ping Health Status",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "-ping google.com",
     "measurement": "app1.database",
     "query": "SELECT \"HealthStatusInt\"  AS IsAlive FROM \"monitor\".\"app11\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "HealthStatusInt" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last PING unhealthy value",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "Status",
     "measurement": "Cortlex.APM.HealthCheсks.AspNetSample.uri-group",
     "select": [
      [
       { "params": [ "HealthStatusString" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "HealthStatusString", "operator": "=", "value": "Degraded" },
      { "condition": "OR", "key": "HealthStatusString", "operator": "=", "value": "Unhealthy" }
     ]
    }
   ]
  },
  {
   "title": "Last DB unhealthy value",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "alias": "Status",
     "measurement": "app1.database",
     "select": [
      [
       { "params": [ "HealthStatusString" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "HealthStatusString", "operator": "=", "value": "Degraded" },
      { "condition": "OR", "key": "HealthStatusString", "operator": "=", "value": "Unhealthy" }
     ]
    }
   ]
  }
 ]
}