{
 "title": "Web Monitoring",
 "description": "Dashboard to visualize metrics captured by App Metrics ASP.NET Core Middleware 1.2.0, tested with App.Metrics.Extensions.Reporting.InfluxDB 1.2.0  - http://app-metrics.io/",
 "tags": [ "influxdb" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": "SHOW TAG VALUES WITH KEY = \"env\""
   },
   {
    "name": "application",
    "query": "SHOW TAG VALUES WITH KEY = \"app\""
   },
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "summarize",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "query": "SHOW TAG VALUES WITH KEY = \"server\""
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "rpm",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Error %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "application.httprequests__one_minute_error_percentage_rate",
     "query": "SELECT  \"value\" FROM \"application.httprequests__percentage_error_requests\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__active",
     "query": "SELECT last(\"value\") FROM \"application.httprequests__active\" WHERE (\"env\" =~ /^$environment$/ AND \"app\" =~ /^$application$/ AND \"server\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Apdex score",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "apdex" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__apdex",
     "select": [
      [
       { "params": [ "score" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate15m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15 min rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "95th Percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p98" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "98th Percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "99th Percentile" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__one_minute_error_percentage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__error_rate",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate15m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15min rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_http_status_code",
     "groupBy": [
      { "params": [ "http_status_code" ], "type": "tag" }
     ],
     "measurement": "application.httprequests__errors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Uncaught Exceptions Thrown",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 24 },
   "targets": [
    {
     "alias": "$tag_exception",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "exception" ], "type": "tag" }
     ],
     "measurement": "application.httprequests__exceptions",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput / Endpoint",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "alias": "$tag_route",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "route" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "application.httprequests__transactions_per_endpoint",
       "select": [
        [
         { "params": [ "rate1m" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Response Time / Endpoint",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_route",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "route" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "application.httprequests__transactions_per_endpoint",
       "select": [
        [
         { "params": [ "p95" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "95th Percentile" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Response Times / Endpoint",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "alias": "$tag_route",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "route" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "application.httprequests__transactions_per_endpoint",
       "select": [
        [
         { "params": [ "p95" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Throughput / Endpoint",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "alias": "$tag_route",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "route" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "application.httprequests__transactions_per_endpoint",
       "select": [
        [
         { "params": [ "rate1m" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Error Request Percentage / Endpoint",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "alias": "$tag_route",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "route" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "application.httprequests__one_minute_error_percentage_rate_per_endpoint",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Uncaught Exceptions Thrown / Endpoint",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "alias": "$tag_route [$tag_exception]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "route" ], "type": "tag" },
        { "params": [ "exception" ], "type": "tag" }
       ],
       "measurement": "application.httprequests__exceptions",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "PUT & POST Request Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Post Request Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "application.httprequests__post_size",
       "select": [
        [
         { "params": [ "p95" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "95th percentile" ], "type": "alias" }
        ],
        [
         { "params": [ "p98" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "98th percentile" ], "type": "alias" }
        ],
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "99th percentile" ], "type": "alias" }
        ],
        [
         { "params": [ "last" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         },
         { "params": [ "median" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Put Request Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "application.httprequests__put_size",
       "select": [
        [
         { "params": [ "p95" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "95th percentile" ], "type": "alias" }
        ],
        [
         { "params": [ "p98" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "98th percentile" ], "type": "alias" }
        ],
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "99th percentile" ], "type": "alias" }
        ],
        [
         { "params": [ "median" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         },
         { "params": [ "median" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
        { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}